### ISSUE TITLE
otomatik oluşan kullanıcı adı

### ISSUE THREAD

**Issue by milisarge** [sonakinci41/Milis-Yukleyici#11]
Yükleyicide kullanıcı adı bölümünde bilgisayar adı kullanıcı adı ile bitişik olarak otomatik oluşuyor. Arada tire işerati olsa daha güzel olur. cihanmilis yerine cihan-milis gibi

**Comment by sonakinci41** [comment]
8d959aaf70a10666cc659df81b30e060c88120ea
